# Generated by Django 5.2.1 on 2025-06-07 17:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('codigo', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=2)),
                ('nome', models.CharField(blank=True, max_length=150, null=True)),
                ('razao_social', models.CharField(blank=True, max_length=150, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='cpf_invalido', message='O CPF deve conter 11 dígitos', regex='^\\d{11}$')])),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='cnpj_invalido', message='O CNPJ deve conter 14 dígitos', regex='^\\d{14}$')])),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('nome_responsavel', models.CharField(max_length=150)),
                ('cargo_responsavel', models.CharField(blank=True, max_length=70, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='telefone_invalido', message='O Telefone deve conter apenas números e ter 10 ou 11 dígitos.', regex='^\\d{10,11}$')])),
                ('data_inicio', models.DateField(default=django.utils.timezone.now)),
                ('data_termino', models.DateField(blank=True, null=True)),
                ('segmento', models.CharField(blank=True, max_length=70, null=True)),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('cep', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(code='cep_invalido', message='O CEP deve conter exatamente 8 números.', regex='^\\d{8}$')])),
                ('logradouro', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_local', models.CharField(blank=True, max_length=15, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('rede_social', models.URLField(blank=True, null=True)),
                ('contrato_parceria', models.FileField(blank=True, null=True, upload_to='parceiro_contratos/')),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembroIabs',
            fields=[
                ('matricula', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('C', 'Colaborador'), ('A', 'Administrador')], default='C', max_length=1)),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='cpf_invalido', message='O CPF deve conter 11 dígitos', regex='^\\d{11}$')])),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo'), ('F', 'Afastado')], default='A', max_length=1)),
                ('cargo', models.CharField(blank=True, max_length=70, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='telefone_invalido', message='O Telefone deve conter apenas números e ter 10 ou 11 dígitos.', regex='^\\d{10,11}$')])),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('R', 'Realizada'), ('A', 'Agendada'), ('C', 'Cancelada')], default='A', max_length=1)),
                ('assunto', models.CharField(max_length=100)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('P', 'Presencial'), ('V', 'Virtual')], max_length=1)),
                ('link_conferencia', models.URLField(blank=True, null=True)),
                ('uf', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(code='cep_invalido', message='O CEP deve conter exatamente 8 números.', regex='^\\d{8}$')])),
                ('logradouro', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_local', models.CharField(blank=True, max_length=15, null=True)),
                ('relatorio', models.FileField(blank=True, null=True, upload_to='reuniao_relatorios/')),
                ('membros', models.ManyToManyField(to='contatos.membroiabs')),
                ('parceiros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contatos.parceiro')),
            ],
        ),
    ]
