# Generated by Django 5.2.1 on 2025-05-24 02:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembroONG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo'), ('F', 'Afastado')], default='A', max_length=1)),
                ('email', models.EmailField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('responsavel_parceiro', models.CharField(max_length=255)),
                ('cargo_responsavel_parceiro', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('tipo_parceiro', models.CharField(max_length=100)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True)),
                ('endereco', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('data_inicio', models.DateField(default=django.utils.timezone.now)),
                ('area_interesse', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
                ('contrato_parceiro', models.CharField(max_length=255)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('membro_ong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contatos.membroong')),
            ],
        ),
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('assunto', models.CharField(max_length=100)),
                ('tipo_reuniao', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('R', 'Realizada'), ('A', 'Agendada'), ('C', 'Cancelada')], default='A', max_length=1)),
                ('participantes', models.TextField()),
                ('relatorio', models.CharField(max_length=200)),
                ('parceiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contatos.parceiro')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipacaoMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membro_ong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contatos.membroong')),
                ('reuniao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contatos.reuniao')),
            ],
        ),
    ]
